# SPDX-FileCopyrightText: 2025 Amritpal Singh <amrit3701@gmail.com>
#
# SPDX-License-Identifier: LGPL-2.0-or-later

services:
  redis:
    image: redis:alpine

  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    depends_on:
      - redis
    ports:
      - "9000:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  celery-worker:
    build:
      context: .
      dockerfile: ./Dockerfile.celery
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BACKEND_URL=${BACKEND_URL:-http://host.docker.internal:3030}
    extra_hosts:
      - "host.docker.internal:host-gateway"
