# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: 2025 Amritpal Singh <amrit3701@gmail.com>


FROM amrit3701/freecad-cli:1.0.2-amd64-ubuntu22.04-py3.11-qt5

# Set working directory
WORKDIR /app

# Copy requirements.txt
COPY requirements/main.txt requirements.txt

# Install dependencies
RUN pip3 install -r requirements.txt

# Expose port for FastAPI
EXPOSE 8080

# Start FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
