# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: 2025 Amritpal Singh <amrit3701@gmail.com>


FROM amrit3701/freecad-cli:0.21-amd64-01.05.2024

# Set working directory
WORKDIR /app

# Copy requirements.txt
COPY requirements/main.txt requirements.txt

# Install dependencies
RUN pip3 install -r requirements.txt --break-system-packages
RUN pip3 install watchdog --break-system-packages

# Start Celery worker
CMD ["watchmedo", "auto-restart", "--directory", ".", "--pattern", "*.py", "--recursive", "--", "celery", "-A", "main.celery", "worker", "--loglevel", "info"]
