# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: 2025 Amritpal Singh <amrit3701@gmail.com>


FROM amrit3701/freecad-cli:1.0.2-amd64-ubuntu22.04-py3.11-qt5

# Set working directory
WORKDIR /app

# Copy requirements.txt
COPY requirements/main.txt requirements.txt

# Install dependencies
RUN pip3 install -r requirements.txt

# Copy code
COPY main.py .
COPY fc_worker ./fc_worker

# Start Celery worker
CMD ["celery", "-A", "main.celery", "worker", "--loglevel", "info"]
